use_frameworks!

target 'SpotifyAPIKit_Example' do
  platform :ios, '11.0'
  pod 'SpotifyAPIKit', :path => '../'
  pod 'Alamofire', '~> 5.2'

  target 'SpotifyAPIKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.2'
  end
end
